// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64
// +build arm64be armbe mips mips64 mips64p32 ppc64 s390 s390x sparc sparc64

package internal

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTproxy returns the embedded CollectionSpec for tproxy.
func loadTproxy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TproxyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tproxy: %w", err)
	}

	return spec, err
}

// loadTproxyObjects loads tproxy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *tproxyObjects
//     *tproxyPrograms
//     *tproxyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTproxyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTproxy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tproxySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tproxySpecs struct {
	tproxyProgramSpecs
	tproxyMapSpecs
}

// tproxySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tproxyProgramSpecs struct {
	BpfSkAssignTest *ebpf.ProgramSpec `ebpf:"bpf_sk_assign_test"`
}

// tproxyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tproxyMapSpecs struct {
	ServerMap *ebpf.MapSpec `ebpf:"server_map"`
}

// tproxyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTproxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type tproxyObjects struct {
	tproxyPrograms
	tproxyMaps
}

func (o *tproxyObjects) Close() error {
	return _TproxyClose(
		&o.tproxyPrograms,
		&o.tproxyMaps,
	)
}

// tproxyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTproxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type tproxyMaps struct {
	ServerMap *ebpf.Map `ebpf:"server_map"`
}

func (m *tproxyMaps) Close() error {
	return _TproxyClose(
		m.ServerMap,
	)
}

// tproxyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTproxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type tproxyPrograms struct {
	BpfSkAssignTest *ebpf.Program `ebpf:"bpf_sk_assign_test"`
}

func (p *tproxyPrograms) Close() error {
	return _TproxyClose(
		p.BpfSkAssignTest,
	)
}

func _TproxyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed tproxy_bpfeb.o
var _TproxyBytes []byte
